import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import SessionProvider from '@/components/providers/SessionProvider'
import { getServerSession } from 'next-auth'

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  variable: '--font-pretendard'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession()
  return (
    <html lang='ko'>
      <body className={`${pretendard.variable} font-pretendard text-[#272727] font-normal`}>
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  )
}
